ci: move from drone ci to github action
Signed-off-by: Chris Chiu <chris.chiu@suse.com>

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,6 +1,18 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM registry.suse.com/bci/bci-base:15.5
 RUN zypper -n rm container-suseconnect && \
     zypper install -y iptables=1.8.7 && \
     zypper -n clean -a && rm -rf /tmp/* /var/tmp/* /usr/share/doc/packages/*
-COPY bin/harvester-network-controller /usr/bin/
+
+ARG TARGETPLATFORM
+
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH=${TARGETPLATFORM#linux/}
+
+COPY bin/harvester-network-controller-${ARCH} /usr/bin/harvester-network-controller
 CMD ["harvester-network-controller"]
diff --git a/package/Dockerfile.helper b/package/Dockerfile.helper
--- a/package/Dockerfile.helper
+++ b/package/Dockerfile.helper
@@ -1,3 +1,15 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM registry.suse.com/bci/bci-minimal:15.5
-COPY bin/harvester-network-helper /usr/bin/
+
+ARG TARGETPLATFORM
+
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH=${TARGETPLATFORM#linux/}
+
+COPY bin/harvester-network-helper-${ARCH} /usr/bin/harvester-network-helper
 CMD ["harvester-network-helper"]
